import type { Metadata } from 'next';
import type { PropsWithChildren } from 'react';
import Footer from './_layout/footer';
import AppHeader from './_layout/header';
import RootProvider from './provider';
import './styles.css';

export const metadata: Metadata = {
  title: 'NextJS Project Template',
  description: 'Generated by Devkitlab',
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body cz-shortcut-listen="true" className="flex flex-col min-h-screen">
        <RootProvider>
          <AppHeader />
          <main className="flex-1 flex flex-col">{children}</main>
          <Footer />
        </RootProvider>
      </body>
    </html>
  );
}
