import '@/styles/index.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  style: 'normal',
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'NextJS Project Starter',
  description: 'Generated by create-next-app and tailwind',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
